stages:
  - build
  - test

include:
  - .gitlab-ci-devenv.yml
  - .gitlab-ci-rules.yml

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  VENV_PATH: "$CI_PROJECT_DIR/venv"
  ECR_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
  SECURE_ANALYZERS_PREFIX: "$ECR_REGISTRY/gitlab/security-products"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  fallback_keys:
    - $CI_DEFAULT_BRANCH
  paths:
    - .cache/

coverage:
  stage: test
  image: $ECR_REGISTRY/docker-hub/cimg/python:3.12.11
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
  variables:
    POETRY_CACHE_DIR: $CI_PROJECT_DIR/.cache
  before_script:
    - python --version
    - poetry --version
    - poetry install
  script:
    - poetry run coverage run
    - poetry run coverage report
    - poetry run coverage xml
    - poetry run coverage html
  cache:
    paths:
      - .cache/
  coverage: '/TOTAL.* (100\%|\d\d\%)$/'
  artifacts:
    paths:
      - htmlcov/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
