---
apiVersion: v1
kind: Namespace
metadata:
  name: "fake-server"
  labels:
    name: "fake-server"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-fake-server
  namespace: argocd
  labels:
    name: identity-fake-server
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/18F/identity-fake-server.git
    targetRevision: stages/agnes
  destination:
    namespace: fake-server
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fake-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fake-server
  minReplicas: 1
  maxReplicas: 16
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1
