---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agnesloadtest/agnes.yaml
- agnesloadtest/lt-myssasp.yaml
- fake-server.yaml
# - prometheus-adapter.yaml
# - dashboard.yaml
- coredns.yaml

