---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agnesloadtest/agnes.yaml
- agnesloadtest/lt-beta_sam_prod.yaml
- agnesloadtest/lt-caia-oidc.yaml
- agnesloadtest/lt-clearinghouse.yaml
- agnesloadtest/lt-dac_prod.yaml
- agnesloadtest/lt-eauth.yaml
- agnesloadtest/lt-fsafeds-mobileapp.yaml
- agnesloadtest/lt-fsafeds.yaml
- agnesloadtest/lt-myssasp.yaml
- agnesloadtest/lt-mytravelgov-cep.yaml
- agnesloadtest/lt-portal-prod.yaml
- agnesloadtest/lt-pspd-ttp-prod.yaml
- agnesloadtest/lt-sol.yaml
- agnesloadtest/lt-usajobs.yaml
- agnesloadtest/lt-vassoerp.yaml
- fake-server.yaml
# - prometheus-adapter.yaml
# - dashboard.yaml
- coredns.yaml

