---
apiVersion: v1
kind: Namespace
metadata:
  name: "loadtest"
  labels:
    name: "loadtest"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loadtest
  namespace: argocd
  labels:
    name: loadtest
spec:
  project: default
  source:
    repoURL: https://github.com/18F/identity-loadtest.git
    path: loadtest
    targetRevision: stages/loadtest
  destination:
    namespace: loadtest
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

