---
apiVersion: v1
kind: Namespace
metadata:
  name: "locust"
  labels:
    name: "locust"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: locust
  namespace: argocd
  labels:
    name: locust
spec:
  project: default
  source:
    chart: locust
    repoURL: https://charts.deliveryhero.io
    targetRevision: 0.30.0
    helm:
      values: |
        loadtest:
          name: login-sign-up-sign-in
          locust_host: https://sp-oidc-sinatra.pt.identitysandbox.gov/
          locust_locustfile_configmap: login-sign-up-sign-in-locustfile
          locust_lib_configmap: login-loadtest-lib
          locust_locustfile: sign_up_sign_in.locustfile.py
          pip_packages:
            - pyquery==1.4.3
  # Destination cluster and namespace to deploy the application
  destination:
    namespace: locust
    server: https://kubernetes.default.svc

  # keep in sync
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
