---
apiVersion: v1
kind: Namespace
metadata:
  name: "locust"
  labels:
    name: "locust"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: locust
  namespace: argocd
  labels:
    name: locust
spec:
  project: default
  source:
    chart: locust
    repoURL: https://charts.deliveryhero.io
    targetRevision: 0.30.0
    helm:
      values: |
        loadtest:
          name: login-sign-up-sign-in
          headless: false
          environment:
            NUM_USERS: "2000000"
                                                  # Ratio numbers are calcualated in proportion
                                                  # to the events/sec requested in the 100x load test plan
            RATIO_SIGN_IN: 7000                   # 2000 events/sec for sign ins
            RATIO_SIGN_IN_USER_NOT_FOUND: 7       #
            RATIO_SIGN_IN_INCORRECT_PASSWORD: 0 #
            RATIO_SIGN_IN_INCORRECT_SMS_OTP: 0  #
            RATIO_SIGN_UP: 1851                   # 500 events/sec for new user registrations
            RATIO_SIGN_IN_AND_PROOF: 0            # 40 - 200 events/sec for identity proofings
            RATIO_SIGN_UP_AND_PROOF: 0            # 700 - 
            SP_HOST: https://oidc-sinatra.loadtest.identitysandbox.gov
          locust_host: https://idp.pt.identitysandbox.gov
          locust_locustfile_configmap: login-locustfiles
          locust_lib_configmap: login-loadtest-lib
          locust_locustfile: prod_simulator.locustfile.py
          pip_packages:
            - coverage==6.2
            - Faker==13.11.1
            - pyquery==1.4.3
            - pyzmq==24.0.1
        # master:
        #   args:
        #     - "-t 6m"
        worker:
          hpa:
            enabled: true
            maxReplicas: 200
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"

  # Destination cluster and namespace to deploy the application
  destination:
    namespace: locust
    server: https://kubernetes.default.svc

  # keep in sync
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
