---
apiVersion: v1
kind: Namespace
metadata:
  name: "locust"
  labels:
    name: "locust"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: locust
  namespace: argocd
  labels:
    name: locust
spec:
  project: default
  source:
    chart: locust
    repoURL: https://charts.deliveryhero.io
    targetRevision: 0.30.0
    helm:
      values: |
        loadtest:
          name: login-sign-up-sign-in
          headless: false
          environment:
            NUM_USERS: "2000000"
                                                  # Ratio numbers are calcualated in proportion
                                                  # to the events/sec requested in the 100x load test plan
            RATIO_SIGN_IN: 7000                   # 2000 events/sec for sign ins
            RATIO_SIGN_IN_USER_NOT_FOUND: 0       # 7
            RATIO_SIGN_IN_INCORRECT_PASSWORD: 0   # 200
            RATIO_SIGN_IN_INCORRECT_SMS_OTP: 0    # 200
            RATIO_SIGN_UP: 1851                   # 1851 = 500 events/sec for new user registrations
            RATIO_SIGN_IN_AND_PROOF: 0            # 40 - 200 events/sec for identity proofings
            RATIO_SIGN_UP_AND_PROOF: 0            # 700 - 
            SP_HOST: https://oidc-sinatra.loadtest.identitysandbox.gov
          locust_host: https://idp.pt.identitysandbox.gov
          locust_locustfile_configmap: login-locustfiles
          locust_lib_configmap: login-loadtest-lib
          locust_locustfile: prod_simulator.locustfile.py
          pip_packages:
            - coverage==6.2
            - Faker==13.11.1
            - pyquery==1.4.3
            - pyzmq==24.0.1
        master:
          nodeSelector:
            eks.amazonaws.com/capacityType: "ON_DEMAND"
          args:
            - "--enable-rebalancing"
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 1500m
              memory: 1024Mi
        worker:
          replicas: 70
          args:
            - "--enable-rebalancing"
          hpa:
            enabled: false
            minReplicas: 10
            maxReplicas: 200
            targetCPUUtilizationPercentage: 95
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
        tolerations:
        - key: "spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"


  # Destination cluster and namespace to deploy the application
  destination:
    namespace: locust
    server: https://kubernetes.default.svc

  # keep in sync
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
