---
apiVersion: v1
kind: Namespace
metadata:
  name: "tstest3"
  labels:
    name: "tstest3"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tstest3
  namespace: argocd
  labels:
    name: tstest3
spec:
  project: default
  source:
    repoURL: https://github.com/18F/identity-loadtest.git
    path: tstest3
    targetRevision: stages/tstest3
  destination:
    namespace: tstest3
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

