---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oidc-sinatra
  annotations:
    external-dns.alpha.kubernetes.io/hostname: SP-oidc-sinatra.CLUSTER_NAME.identitysandbox.gov
spec:
  tls:
    - hosts:
        - SP-oidc-sinatra.CLUSTER_NAME.identitysandbox.gov
