version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.3
    working_directory: ~/identity-loadtest
    steps:
      - checkout
      - restore_cache:
          key: v1-identity-loadtest-pip-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run: pip install -r requirements.txt
      - save_cache:
          key: v1-identity-loadtest-pip-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run: coverage run -m pytest
      - run: coverage report

workflows:
  build:
    jobs:
      - build
