
- op: replace
  path: /spec/template/spec/containers/0/env/0
  value:
    name: idp_url
    value: "https://idp.sftest.identitysandbox.gov/"
- op: replace
  path: /spec/template/spec/containers/0/env/1
  value:
    name: redirect_uri
    value: "https://sftest-oidc-sinatra.agnesloadtest.identitysandbox.gov/"
- op: replace
  path: /spec/template/spec/containers/0/env/2
  value:
    name: NEW_RELIC_APP_NAME
    value: sftest-oidc-sinatra.agnesloadtest.identitysandbox.gov
