---
apiVersion: v1
kind: Namespace
metadata:
  name: "oidc-sinatra"
  labels:
    name: "oidc-sinatra"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-sinatra
  namespace: argocd
  labels:
    name: oidc-sinatra
spec:
  project: default
  source:
    path: oidc-sinatra
    repoURL: https://github.com/18F/identity-loadtest.git
    targetRevision: stages/agnes
  destination:
    namespace: oidc-sinatra
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
  template:
    metadata:
      labels:
        app: oidc-sinatra
    spec:
      containers:
        - name: oidc-sinatra
          image: 894947205914.dkr.ecr.us-west-2.amazonaws.com/logindotgov/oidc-sinatra:1.4
          env:
            - name: idp_url
              value: "https://idp.agnes.identitysandbox.gov/"
            - name: acr_values
              value: "http://idmanagement.gov/ns/assurance/loa/1"
            - name: redirect_uri
              value: "https://oidc-sinatra.agnesloadtest.identitysandbox.gov/"
            - name: client_id
              value: "urn:gov:gsa:openidconnect:sp:sinatra"
            - name: sp_private_key
              valueFrom:
                secretKeyRef:
                  name: sp-private-key
                  key: demo_sp.key
                  optional: false
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic-license
                  key: newrelic-license
                  optional: false
            - name: NEW_RELIC_HOST
              value: gov-collector.newrelic.com
            - name: RACK_ENV
              value: production
            - name: cache_oidc_config
              value: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "160Mi"
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 9292
      tolerations:
        - key: "spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

