apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: tstest3-
resources:
  - locust.yaml
  - ../oidc-sinatra
  - ../load_testing
patches:
  - path: patch-oidc-ingress.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: tstest3
    unsetOnly: true
