---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oidc-sinatra
  annotations:
    external-dns.alpha.kubernetes.io/hostname: lt-portal-prod-oidc-sinatra.agnesloadtest.identitysandbox.gov
spec:
  tls:
    - hosts:
        - lt-portal-prod-oidc-sinatra.agnesloadtest.identitysandbox.gov
