apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: pt-
resources:
  - ../locust
  - ../oidc-sinatra
  - ../load_testing

patches:
  - path: patch-locust.yaml
  - path: patch-oidc-ingress.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: pt
    unsetOnly: true

