---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: locust
  namespace: argocd
  labels:
    name: locust
spec:
  source:
    helm:
      values: |
        loadtest:
          name: production_simulator
          headless: false
          environment:
            SP_HOST: https://oidc-sinatra.loadtest.identitysandbox.gov
            NUM_USERS: "5000000" # 5M
            RATIO_SIGN_IN: 3812
            RATIO_SIGN_IN_INCORRECT_PASSWORD: 900
            RATIO_SIGN_IN_INCORRECT_SMS_OTP: 23
            RATIO_SIGN_UP: 275
            RATIO_SIGN_UP_AND_PROOF: 4990

          locust_host: https://idp.pt.identitysandbox.gov
          locust_locustfile_configmap: pt-login-locustfiles
          locust_lib_configmap: pt-login-loadtest-lib
          locust_locustfile: prod_simulator.locustfile.py
          pip_packages:
            - coverage==7.5.3
            - Faker==25.4.0
            - pyquery==2.0.0
            - pytest==8.2.1
            - pyzmq==26.0.3
        master:
          image: 894947205914.dkr.ecr.us-west-2.amazonaws.com/locustio/locust:2.32.4
          nodeSelector:
            eks.amazonaws.com/capacityType: "ON_DEMAND"
          args:
            - "--enable-rebalancing --loglevel DEBUG"
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          resources:
            limits:
              cpu: 3000m
              memory: 3000Mi
            requests:
              cpu: 1500m
              memory: 1500Mi
        worker:
          image: 894947205914.dkr.ecr.us-west-2.amazonaws.com/locustio/locust:2.32.4
          replicas: 440
          args:
            - "--enable-rebalancing"
          hpa:
            enabled: false
            minReplicas: 1
            maxReplicas: 512
            targetCPUUtilizationPercentage: 80
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
        tolerations:
        - key: "spot"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

  # Destination cluster and namespace to deploy the application
  destination:
    namespace: pt
