---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oidc-sinatra
  annotations:
    external-dns.alpha.kubernetes.io/hostname: loadtest-oidc-sinatra.loadtest.identitysandbox.gov
spec:
  tls:
    - hosts:
        - loadtest-oidc-sinatra.loadtest.identitysandbox.gov
