---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oidc-sinatra
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mww59-oidc-sinatra.mww59loadtest.identitysandbox.gov
spec:
  tls:
    - hosts:
        - mww59-oidc-sinatra.mww59loadtest.identitysandbox.gov
